# Comp 3

Peter Vanya

Jarná škola FX, marec 2016

## Program na dnes
Práca so súbormi, tlačenie a načítanie dát.

## Za pomoci numpy

Najjednoduchší spôsob za pomoci dvoch príkazov: `np.loadtxt` a `np.savetxt`.

In [1]:
# najjednoduchsi sposob
import numpy as np
import os

a = np.arange(10)
print(a)
fname = "subor.out"
np.savetxt(fname, a)   # vektor ulozeny v subor.out
os.listdir(".")        # je tam, ale pozor na formatovanie

[0 1 2 3 4 5 6 7 8 9]


['.git',
 '.ipynb_checkpoints',
 'comp1.ipynb',
 'comp1.py',
 'comp2.ipynb',
 'comp2.py',
 'comp3.ipynb',
 'comp3.py',
 'comp4.ipynb',
 'comp4.py',
 'dump.xyz',
 'eminem.out',
 'JSFX16_projects.pdf',
 'linalg_lect_old.ipynb',
 'README.md',
 'subor.out',
 'veta.out']

In [2]:
cat subor.out

0.000000000000000000e+00
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
5.000000000000000000e+00
6.000000000000000000e+00
7.000000000000000000e+00
8.000000000000000000e+00
9.000000000000000000e+00


In [5]:
# opatovne nacitanie
b = np.loadtxt("subor.out")
b    # premena z int na float

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

## Štandardný Python

In [10]:
veta = "toto je veta"
fname = "veta.out"

# spravny sposob
with open(fname, "w") as f:
    f.write(veta)
        
# alebo na jeden riadok
open(fname, "w").write(veta + "42" + veta)

26

In [7]:
# nacitanie
veta = open(fname, "r").read()
print(veta)
print(len(veta))    # dlzka

toto je veta42toto je veta
26


## Operácie so stringom [Adv 1]
Python má perfektné možnosti manipulácie stringov, stojí za to sa ich naučiť (napr. ak raz budete chcieť scrapovať internet alebo "čítať" emaily)

In [12]:
print(veta)
print(veta.split())              # rozdel podla medzier
print(veta.split("t"))           # rozdel podla znaku t

toto je veta
['toto', 'je', 'veta']
['', 'o', 'o je ve', 'a']


In [15]:
print("_333_".join(veta.split()))    # spoj naspat podla zelaneho znaku

toto_333_je_333_veta


Realny text:

In [2]:
fname = "eminem.out"
lyric = open(fname, "r").read()
print(len(lyric))                   # pocet znakov
print(len(lyric.split()))           # pocet slov

3357
654


In [3]:
# inak
lyric = open(fname, "r").readlines()
len(lyric)        # pocet riadkov

88

In [4]:
print(lyric[:50])

['"Lose Yourself"\n', '\n', 'Look, if you had, one shot, or one opportunity\n', 'To seize everything you ever wanted. In one moment\n', 'Would you capture it, or just let it slip?\n', 'Yo\n', '\n', 'His palms are sweaty, knees weak, arms are heavy\n', "There's vomit on his sweater already, mom's spaghetti\n", "He's nervous, but on the surface he looks calm and ready to drop bombs,\n", 'But he keeps on forgetting what he wrote down,\n', 'The whole crowd goes so loud\n', "He opens his mouth, but the words won't come out\n", "He's choking how, everybody's joking now\n", "The clock's run out, time's up, over, blaow!\n", 'Snap back to reality. Oh, there goes gravity\n', 'Oh, there goes Rabbit, he choked\n', "He's so mad, but he won't give up that\n", 'Easy, no\n', "He won't have it, he knows his whole back's to these ropes\n", "It don't matter, he's dope\n", "He knows that but he's broke\n", "He's so sad that he knows\n", "When he goes back to his mobile home, that's when it's\n", 'Back to 

In [5]:
# najdime nejake slovo
word = "mother"
zoznam_riadkov = [l for l in lyric if word in l]
zoznam_riadkov

['Tear this motherfucking roof off like two dogs caged\n',
 "Success is my only motherfucking option, failure's not\n"]

In [6]:
[i**2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [7]:
lyric = open("eminem.out", "r").readlines()
#print(lyric[:100])
hot_vety = [l for l in lyric if "hot" in l]
hot_slova = [slovo for slovo in " ".join(hot_vety).split() if "hot" in slovo]
print(hot_slova)
hot_slova = [s.rstrip(".") for s in hot_slova]
hot_slova = [s.rstrip(",") for s in hot_slova]
hot_slova



['shot,', 'shot,', 'shot,', 'hotter', 'shot', 'shot.']


['shot', 'shot', 'shot', 'hotter', 'shot', 'shot']

## Reálne dáta

Zoberme si xyz súbor `dump.xyz`.
* Prvy riadok: počet atómov
* Druhý riadok: komentár
* Zvyšné riadky: typ atómu a súradnice

In [9]:
cat dump.xyz

20
Atoms. Timestep: 0
1 1.12579e-08 2.02559e-08 1.42524e-08
1 1.094e-08 2.0351e-08 1.37532e-08
1 1.06093e-08 2.08093e-08 1.36298e-08
2 1.02329e-08 2.06154e-08 1.38708e-08
3 9.9807e-09 2.01773e-08 1.43359e-08
1 9.90293e-09 1.93784e-08 1.43204e-08
1 9.75859e-09 2.00558e-08 1.46675e-08
1 9.92161e-09 2.07367e-08 1.43633e-08
2 9.60101e-09 2.05323e-08 1.48212e-08
3 9.5146e-09 2.10736e-08 1.42384e-08
1 9.88079e-09 2.09729e-08 1.38977e-08
1 9.63685e-09 2.10999e-08 1.45368e-08
1 9.24626e-09 2.13127e-08 1.46208e-08
2 9.58693e-09 2.17385e-08 1.47513e-08
3 9.54441e-09 2.25182e-08 1.4969e-08
1 9.46635e-09 2.21348e-08 1.56699e-08
1 9.33187e-09 2.14316e-08 1.53606e-08
1 9.73877e-09 2.14188e-08 1.53489e-08
2 9.58312e-09 2.06738e-08 1.54521e-08
3 9.91561e-09 2.03269e-08 1.57685e-08


In [10]:
fname = "dump.xyz"
A = open(fname).readlines()
A[:2]

['20\n', 'Atoms. Timestep: 0\n']

In [11]:
A[2:]

['1 1.12579e-08 2.02559e-08 1.42524e-08\n',
 '1 1.094e-08 2.0351e-08 1.37532e-08\n',
 '1 1.06093e-08 2.08093e-08 1.36298e-08\n',
 '2 1.02329e-08 2.06154e-08 1.38708e-08\n',
 '3 9.9807e-09 2.01773e-08 1.43359e-08\n',
 '1 9.90293e-09 1.93784e-08 1.43204e-08\n',
 '1 9.75859e-09 2.00558e-08 1.46675e-08\n',
 '1 9.92161e-09 2.07367e-08 1.43633e-08\n',
 '2 9.60101e-09 2.05323e-08 1.48212e-08\n',
 '3 9.5146e-09 2.10736e-08 1.42384e-08\n',
 '1 9.88079e-09 2.09729e-08 1.38977e-08\n',
 '1 9.63685e-09 2.10999e-08 1.45368e-08\n',
 '1 9.24626e-09 2.13127e-08 1.46208e-08\n',
 '2 9.58693e-09 2.17385e-08 1.47513e-08\n',
 '3 9.54441e-09 2.25182e-08 1.4969e-08\n',
 '1 9.46635e-09 2.21348e-08 1.56699e-08\n',
 '1 9.33187e-09 2.14316e-08 1.53606e-08\n',
 '1 9.73877e-09 2.14188e-08 1.53489e-08\n',
 '2 9.58312e-09 2.06738e-08 1.54521e-08\n',
 '3 9.91561e-09 2.03269e-08 1.57685e-08\n']

In [12]:
B = A[2:]
B = [[float(i) for i in line.split()] for line in B]

# Pozor! V numpy maticiach nemozno spravit jeden stlpec typu int
# a iny typu float
#B[:, 0] = [int(B[i, 0]) for i in B[:, 0]]
#B[:, 0] = B[:, 0].astype(int)   # nejde
B

[[1.0, 1.12579e-08, 2.02559e-08, 1.42524e-08],
 [1.0, 1.094e-08, 2.0351e-08, 1.37532e-08],
 [1.0, 1.06093e-08, 2.08093e-08, 1.36298e-08],
 [2.0, 1.02329e-08, 2.06154e-08, 1.38708e-08],
 [3.0, 9.9807e-09, 2.01773e-08, 1.43359e-08],
 [1.0, 9.90293e-09, 1.93784e-08, 1.43204e-08],
 [1.0, 9.75859e-09, 2.00558e-08, 1.46675e-08],
 [1.0, 9.92161e-09, 2.07367e-08, 1.43633e-08],
 [2.0, 9.60101e-09, 2.05323e-08, 1.48212e-08],
 [3.0, 9.5146e-09, 2.10736e-08, 1.42384e-08],
 [1.0, 9.88079e-09, 2.09729e-08, 1.38977e-08],
 [1.0, 9.63685e-09, 2.10999e-08, 1.45368e-08],
 [1.0, 9.24626e-09, 2.13127e-08, 1.46208e-08],
 [2.0, 9.58693e-09, 2.17385e-08, 1.47513e-08],
 [3.0, 9.54441e-09, 2.25182e-08, 1.4969e-08],
 [1.0, 9.46635e-09, 2.21348e-08, 1.56699e-08],
 [1.0, 9.33187e-09, 2.14316e-08, 1.53606e-08],
 [1.0, 9.73877e-09, 2.14188e-08, 1.53489e-08],
 [2.0, 9.58312e-09, 2.06738e-08, 1.54521e-08],
 [3.0, 9.91561e-09, 2.03269e-08, 1.57685e-08]]

## Alternatívne...

... vyrobme si objekt a uložme atómové typy a xyz maticu do rôznych atribútov.

In [14]:
class xyzMatica():
    def __init__(self):
        self.types = []
        self.xyz = np.array([[]])
        self.pozdrav = "ahoj Fero"
    
    def read(self, fname):
        A = open(fname).readlines()
        A = [line.split() for line in A[2:]]
        A = np.array(A).astype(float)
        self.types = A[:, 0].astype(int)
        self.xyz = A[:, 1:4]
        

In [15]:
moja_matica = xyzMatica()
moja_matica.types

[]

In [16]:
moja_matica.xyz

array([], shape=(1, 0), dtype=float64)

In [17]:
# teraz do objektu nacitajme data
mat = xyzMatica()
mat.read("dump.xyz")
mat.types

array([1, 1, 1, 2, 3, 1, 1, 1, 2, 3, 1, 1, 1, 2, 3, 1, 1, 1, 2, 3])

***
## [Problem]

Načítajte *Lose yourself* a nájdite počet prázdnych riadkov.
***

In [18]:
lyric = open("eminem.out", "r").readlines()
prazdne = [line for line in lyric if line == "\n"]
len(prazdne)

8